### ISSUE TITLE
[i18n] Analog item with no unit - TcMenu throws exception

### ISSUE THREAD

**Issue by vzahradnik** [davetcc/tcMenu#342]
**Describe the bug**
This issue occurrs in the experimental build with i18n support. After the feature is activated, TcMenu designer doesn´t allow to click on the analog menu item. Instead it logs an exception. There is no crash but the designer window is not switched to the selected menu item.

**Commerical or Personal use**
Commercial use.

**To Reproduce**
Steps to reproduce the behavior, if a UI issue please detail all steps and include an example project if needed.
If a library issue provide whatever is needed in order for me to quickly identify the cause.

Here is the problematic config:
```
    {
      "parentId": 71,
      "type": "analogItem",
      "defaultValue": "0",
      "item": {
        "maxValue": 65535,
        "offset": 0,
        "divisor": 1,
        "unitName": "",
        "step": 1,
        "name": "Photoresistor",
        "variableName": "PhotoresistorValue",
        "id": 72,
        "eepromAddress": -1,
        "readOnly": true,
        "localOnly": false,
        "visible": true,
        "staticDataInRAM": false
      }
    },
```

As I found out, the problem occurrs only when the `AnalogMenuItem` has no unit assigned. In this case I read raw sensor value without any processing.

Here is the problematic code:
```java
default String getFromLocaleWithDefault(String localeEntry, String defText) {
        if(!isLocalSupportEnabled() || !localeEntry.startsWith("%") && localeEntry.length() > 1) return defText;
        if(getCurrentLocale().getLanguage().equals("--")) return defText;
        String ret = getLocalSpecificEntry(localeEntry.substring(1));
        return (ret == null) ? defText : ret;
    }
```

And the full error stack trace:

```java
Exception in thread "JavaFX Application Thread" java.lang.StringIndexOutOfBoundsException: Range [1, 0) out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4608)
	at java.base/java.lang.String.substring(String.java:2720)
	at java.base/java.lang.String.substring(String.java:2693)
	at com.thecoderscorner.tcmenu.javaapi/com.thecoderscorner.menu.persist.LocaleMappingHandler.getFromLocaleWithDefault(LocaleMappingHandler.java:23)
	at com.thecoderscorner.tcmenu.javaapi/com.thecoderscorner.menu.domain.util.MenuItemFormatter.bundleIfPossible(MenuItemFormatter.java:31)
	at com.thecoderscorner.tcmenu.javaapi/com.thecoderscorner.menu.domain.util.MenuItemFormatter.formatAnalogForDisplay(MenuItemFormatter.java:203)
	at com.thecoderscorner.tcmenu.javaapi/com.thecoderscorner.menu.domain.util.MenuItemFormatter.formatForDisplay(MenuItemFormatter.java:145)
	at com.thecoderscorner.tcmenu.menuEditorUI/com.thecoderscorner.menu.editorui.uimodel.UIAnalogMenuItem.populateMinMaxLabel(UIAnalogMenuItem.java:207)
	at com.thecoderscorner.tcmenu.menuEditorUI/com.thecoderscorner.menu.editorui.uimodel.UIAnalogMenuItem.internalInitPanel(UIAnalogMenuItem.java:110)
	at com.thecoderscorner.tcmenu.menuEditorUI/com.thecoderscorner.menu.editorui.uimodel.UIMenuItem.initPanel(UIMenuItem.java:224)
	at com.thecoderscorner.tcmenu.menuEditorUI/com.thecoderscorner.menu.editorui.controller.MenuEditorController.lambda$onTreeChangeSelection$10(MenuEditorController.java:271)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196)
	at com.thecoderscorner.tcmenu.menuEditorUI/com.thecoderscorner.menu.editorui.controller.MenuEditorController.onTreeChangeSelection(MenuEditorController.java:270)
	at com.thecoderscorner.tcmenu.menuEditorUI/com.thecoderscorner.menu.editorui.controller.MenuEditorController.lambda$initialise$2(MenuEditorController.java:136)
	at javafx.base@20/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at javafx.base@20/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base@20/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:80)
	at javafx.base@20/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.base@20/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base@20/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at javafx.controls@20/javafx.scene.control.SelectionModel.setSelectedItem(SelectionModel.java:105)
	at javafx.controls@20/javafx.scene.control.MultipleSelectionModelBase.lambda$new$0(MultipleSelectionModelBase.java:67)
	at javafx.base@20/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
	at javafx.base@20/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base@20/javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(ReadOnlyIntegerPropertyBase.java:78)
	at javafx.base@20/javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:102)
	at javafx.base@20/javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:114)
	at javafx.base@20/javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.controls@20/javafx.scene.control.SelectionModel.setSelectedIndex(SelectionModel.java:69)
	at javafx.controls@20/javafx.scene.control.MultipleSelectionModelBase.select(MultipleSelectionModelBase.java:424)
	at javafx.controls@20/javafx.scene.control.MultipleSelectionModelBase.clearAndSelect(MultipleSelectionModelBase.java:371)
	at javafx.controls@20/javafx.scene.control.TreeView$TreeViewBitSetSelectionModel.clearAndSelect(TreeView.java:1596)
	at javafx.controls@20/com.sun.javafx.scene.control.behavior.CellBehaviorBase.simpleSelect(CellBehaviorBase.java:287)
	at javafx.controls@20/com.sun.javafx.scene.control.behavior.CellBehaviorBase.doSelect(CellBehaviorBase.java:246)
	at javafx.controls@20/com.sun.javafx.scene.control.behavior.CellBehaviorBase.mousePressed(CellBehaviorBase.java:176)
	at javafx.controls@20/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base@20/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base@20/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base@20/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@20/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@20/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@20/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@20/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@20/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@20/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@20/javafx.scene.Scene$MouseHandler.process(Scene.java:3980)
	at javafx.graphics@20/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.graphics@20/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2704)
	at javafx.graphics@20/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@20/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@20/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@20/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@20/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@20/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@20/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@20/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@20/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
```

**Expected behavior**

I can edit the Analog menu item in the designer and there is no exception in the logs.

**Screenshots**
![Snímka obrazovky zo dňa 2023-04-30 17-54-31](https://user-images.githubusercontent.com/4460766/235363058-bdd46735-a313-4fb1-8b29-4f00f464b20c.png)
> Note that the right pane is still on the `BatteryVoltage` despite another item was clicked on the left.

**Desktop UI issue (please complete the following information):**
 - OS: All; reproduced on Windows 11 and Linux
 - Version Win11, Ubutu 23.04, Arch Linux
 - Output of diagnostics from tcMenuDesigner - not needed. See traces above.
 - Designer Version and any other relevant details - experimental beta

**Embedded environment
 Provide as much information as possible about the board configuration here.
- N/A

**Additional context**
- N/A

**Comment by davetcc** [comment]
Yep, I noticed this myself just the other day. I think I worked out what's wrong but haven't had a chance to test it properly yet.

**Comment by davetcc** [comment]
I've had a go at this after a code walkthrough I noticed a couple of errors, it may be worth you looking through the commit for this issue to see if it looks right

**Comment by vzahradnik** [comment]
I'll check tomorrow. Thanks!

**Comment by vzahradnik** [comment]
@davetcc I confirmed your fix solves this problem. I found another but I'll create a separate issue for it.

**Comment by davetcc** [comment]
I found the underlying bug with this, and reopened it to do the commit.

**Comment by davetcc** [comment]
Done, this item should be fully fixed now
